# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  nugetConfigFile: '$(Build.SourcesDirectory)/nuget.config'

steps:
- checkout: self
  submodules: true
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: '$(nugetConfigFile)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  
- task: BatchScript@1
  inputs:
    filename: 'Test.bat'
  
- task: MSBuild@1
  inputs:
    solution: 'ConsoleApp.Installer\ConsoleApp.Installer.wixproj'
    platform: 'x86'
    configuration: 'Debug'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_ivan-srsen'
    repositoryName: 'ivan-srsen/pipeline'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- publish: $(System.DefaultWorkingDirectory)
  artifact: WebApp

- download: current
  artifact: WebApp